# Generated by Django 4.2.4 on 2023-09-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_producto_subcategoria_alter_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
    ]
